create TABLE authlogs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   username VARCHAR,
   description VARCHAR,
   time timestamptz DEFAULT current_timestamp,
   CONSTRAINT pk_authlogs PRIMARY KEY (id)
);